import { Fellow } from './types'

export const FELLOWS: Fellow[] = [
  { id: 'p-12', name: 'Messier', bio: 'AI engineer & creative technologist. Music producer. Chaos architect.', photo_url: '/avatars/messier.jpg', socials: { twitter: 'rssmrm', instagram: 'mara.ipynb' } },
  { id: 'p-40', name: 'Kat (the vat)', bio: 'Multi-disciplinary creator, 25. Into ARGs, DAOs, networked organisms.', photo_url: '/avatars/kat.jpg', socials: {} },
  { id: 'p-1', name: 'Emily', bio: 'From Bristol, UK. AI Safety Camp alum, TTRPG designer, content creator.', photo_url: '/avatars/emily.png', socials: { youtube: 'FrodgePodge1398' } },
  { id: 'p-2', name: 'Evan', bio: 'CS student from Ontario. Curator of fashion, music and philosophical ideas.', photo_url: '', socials: {} },
  { id: 'p-3', name: 'Ana', bio: 'Temple University. Filmmaker, animator, game developer.', photo_url: '/avatars/ana.png', socials: {} },
  { id: 'p-4', name: 'Michelle Huang', bio: 'Artist-researcher running an art collective nonprofit in rural Japan.', photo_url: '/avatars/michelle_huang.jpg', socials: { twitter: 'michellehuang42' } },
  { id: 'p-5', name: 'Matthew', bio: 'From Sydney, Australia. Uni student and PDKU player.', photo_url: '/avatars/matthew.jpg', socials: {} },
  { id: 'p-6', name: 'Savannah', bio: 'Las Vegas. Short films, paintings, photography on mental health and AI ethics.', photo_url: '/avatars/savannah.jpg', socials: { instagram: 'savannah_raisor' } },
  { id: 'p-7', name: 'Becca', bio: 'From Philadelphia. Yoga teacher, singing teacher. AI content for non-technical audiences.', photo_url: '/avatars/becca.jpg', socials: {} },
  { id: 'p-8', name: 'Tyler Alterman', bio: 'NYC. Novelist, contact improv dancer, community builder at Fractal NYC.', photo_url: '/avatars/tyler.jpg', socials: {} },
  { id: 'p-9', name: 'Eugene', bio: 'Social butterfly, 23. Behavioral biology, fighting for people left behind.', photo_url: '/avatars/eugene.jpg', socials: { instagram: 'eugene_affirmative' } },
  { id: 'p-10', name: 'Aaron Silverbook', bio: '', photo_url: '/avatars/aaron.jpg', socials: {} },
  { id: 'p-11', name: 'KT', bio: 'Budapest. Human psychology, group dynamics. Cozy introvert vibes.', photo_url: '', socials: {} },
  { id: 'p-13', name: 'Isabel', bio: 'Australia/Singapore. Creative technologist. Built napole0n.ai.', photo_url: '/avatars/isabel.jpg', socials: { instagram: 'artificial.isabel' } },
  { id: 'p-14', name: 'Jessiah', bio: 'Mendocino, CA. Former English lit teacher, now data science. Life coach.', photo_url: '/avatars/jessiah.jpg', socials: {} },
  { id: 'p-15', name: 'Avisha', bio: 'NY. Signal processing + AI. Runs @distilledscience.', photo_url: '/avatars/avisha.jpg', socials: { instagram: 'distilledscience' } },
  { id: 'p-16', name: 'Francesca (Pixel Surfer)', bio: 'San Diego. Ex-Microsoft SWE, musician, surfer/surfboard shaper.', photo_url: '/avatars/francesca.jpg', socials: {} },
  { id: 'p-17', name: 'Eliana', bio: 'USC acting alum, West LA. Singer, Ableton user, stand-up comedian.', photo_url: '/avatars/eliana.jpg', socials: { twitter: 'yellieyana' } },
  { id: 'p-18', name: 'Elwyn', bio: 'Florida. Former comedy video creator. Mindful content.', photo_url: '', socials: {} },
  { id: 'p-19', name: 'Justin Kuiper', bio: 'Sacramento. Scriptwriter for Game Theory (~1B views). Substack + YouTube.', photo_url: '/avatars/justin.png', socials: {} },
  { id: 'p-20', name: 'Michelle (mee-chell)', bio: 'Mexico, now in Sedona. Cognitive science (consciousness), pursuing MA/MFA.', photo_url: '', socials: {} },
  { id: 'p-21', name: 'Tonchi', bio: 'Santiago, Chile. 19yo law student, STEM activist. Nickelodeon award winner.', photo_url: '/avatars/tonchi.jpg', socials: { instagram: 'tonchimatta' } },
  { id: 'p-22', name: 'Brenda', bio: 'Costa Rica, now California. Hacker house. AI for women\'s health.', photo_url: '', socials: {} },
  { id: 'p-23', name: 'Gai', bio: 'Japan, hippie commune in West County CA. Traveler, hitchhiker, 2D animator.', photo_url: '/avatars/gai.png', socials: {} },
  { id: 'p-24', name: 'Aryeh', bio: 'Columbus, OH. Fishtank Season 4 alum, aspiring video essayist.', photo_url: '/avatars/aryeh.jpg', socials: { twitter: 'R_YayOFFICIAL' } },
  { id: 'p-25', name: 'Glasha', bio: 'Buffalo, NY. From Moscow. Philosophy grad, EA, AI risk comms.', photo_url: '/avatars/glasha.jpg', socials: {} },
  { id: 'p-26', name: 'Charlie Guthmann', bio: 'Chicago/Philly. Econ/AI/progress. Biking Chicago to PDKU interviewing people.', photo_url: '/avatars/charlie.png', socials: {} },
  { id: 'p-27', name: 'Christian Gonzalez', bio: 'NJ/Barcelona/Montreal. Physics, philosophy, ML. Philosophy podcast.', photo_url: '/avatars/christian.jpg', socials: { twitter: 'cxgonzalez' } },
  { id: 'p-28', name: 'Aron Fromm', bio: 'LA. Entertainment/animation. Worked on "Smiling Friends". Restores animatronics.', photo_url: '/avatars/aron.jpg', socials: { twitter: 'aronfromm' } },
  { id: 'p-29', name: 'Jeredino Lavagnino', bio: 'Retired blogger, aspiring video creator. Werner Herzog fan. Literary criticism.', photo_url: '/avatars/jeredino.jpg', socials: {} },
  { id: 'p-30', name: 'Halina', bio: 'Bay Area. Blockchain, decentralized governance. 70k followers.', photo_url: '/avatars/halina.jpg', socials: { twitter: 'halina_eth' } },
  { id: 'p-31', name: 'Josie', bio: 'Mexican-American from Alabama, based in Malaysia. Content creator.', photo_url: '/avatars/josie.jpg', socials: { instagram: 'josiefiguresitout' } },
  { id: 'p-32', name: 'Future Briefing', bio: 'London/Canada. AI Safety comms (BlueDot, FLI).', photo_url: '/avatars/caitlin_y.jpg', socials: { twitter: 'YardleyCaitlin' } },
  { id: 'p-33', name: 'Tess', bio: 'Berkeley. Gap year after Stanford PhD. Pivoting to AI safety.', photo_url: '/avatars/tess.jpg', socials: { twitter: 'thegartsy' } },
  { id: 'p-34', name: 'Tanner', bio: 'Appalachian Ohio. Geologist. Former Geometry Dash YouTuber.', photo_url: '/avatars/tanner.jpg', socials: {} },
  { id: 'p-35', name: 'Oliver', bio: 'LA. 3D motion graphics about AI. Film festival shorts.', photo_url: '/avatars/oliver.jpg', socials: {} },
  { id: 'p-36', name: 'Brogan (Art Chad)', bio: 'Toronto. Video essays about art, culture, tech. CCCRU studio.', photo_url: '/avatars/brogan.jpg', socials: {} },
  { id: 'p-37', name: 'Caitlin (Has Questions)', bio: 'Michigan. Music education, opera, ex-creative director for a Senator.', photo_url: '/avatars/caitlin_q.png', socials: {} },
  { id: 'p-38', name: 'John (Broomhead)', bio: 'SF. Eco-luddite turned tech optimist. AI safety via climate policy.', photo_url: '', socials: {} },
  { id: 'p-39', name: 'Josh', bio: 'Founded UBC AI safety group. AI governance research. TikToks about AI safety.', photo_url: '/avatars/josh.jpg', socials: {} },
  { id: 'p-41', name: 'Camden', bio: 'Boston, 23. CS grad. Music producer (hyperpop/math-rock/metal), theater.', photo_url: '/avatars/camden.jpg', socials: {} },
  { id: 'p-43', name: 'Loan (DD)', bio: 'Vietnam/Seattle. ML forecasting at Google/Apple. 3D printing, yoga.', photo_url: '', socials: {} },
  { id: 'p-44', name: 'Jennifer', bio: 'Oakland. Artist and maker. Physical objects, learning video from scratch.', photo_url: '', socials: {} },
  { id: 'p-45', name: 'Evie', bio: 'Latvia/NYC. Forbes 30 Under 30. AI/robotics content creator.', photo_url: '/avatars/evie.jpg', socials: {} },
  { id: 'p-46', name: 'Ali', bio: 'NYC. Backend SWE, Threat Wire host on Hak5 (1M subs). DJ, cybersecurity.', photo_url: '/avatars/ali.jpg', socials: { twitter: 'endingwithali' } },
  { id: 'p-47', name: 'conq', bio: 'ETH Zurich AI student. Substack essayist. New to video.', photo_url: '/avatars/conq.jpg', socials: { twitter: 'serialsevens' } },
  { id: 'p-48', name: 'Avalon', bio: '1.2M followers. BuzzFeed alum. Star Wars Unlimited player. Vibe coder.', photo_url: '/avatars/avalon.jpg', socials: { instagram: 'avalonwarrenn' } },
  { id: 'p-49', name: 'Xander', bio: 'UK. 200k+ followers. Lore.Nerd (movies) and philosophy content.', photo_url: '/avatars/xander.jpg', socials: {} },
  { id: 'p-50', name: 'Kyle', bio: 'Boring, Oregon/Berkeley. Contact improv dancer, meditator, monastery veteran.', photo_url: '/avatars/kyle.jpg', socials: {} },
  { id: 'p-51', name: 'Maëlle', bio: 'Franco-American filmmaker. La Fémis grad. Animation, AI generation.', photo_url: '/avatars/maelle.jpg', socials: {} },
  { id: 'p-52', name: 'Johannes Rolshausen', bio: 'Saarbrücken, Germany. Actor, Gen-AI security engineer.', photo_url: '', socials: {} },
]
